
a = float(input("masukkan nilai a: "))
b = float(input("masukkan nilai b: "))

print()
print("nilai a =", a)
print("tipe data a:", type(a))
print()
print("nilai b =",b)
print("tipe data b:",type(b))
print()
print()
print("/n=== hasi operasi mtematika===")
print()
print(f"a+b={a+b}")
print(f"a-b={a-b}")
print()
print(f"a*b={a*b}")
print(f"a*2+b2={a2+b*2}")
print()
print(f"a%b={a%b}")
print(f"b%a={b%a}")
print()
print(f"a//b={a//b}")
print(f"b//a={b//a}")
